const GET_CAR_DATA = "GET_CAR_DATA";
const SEARCH_CAR_DATA = "SEARCH_CAR_DATA";
const EMAIL_DATA = "EMAIL_DATA";
const SET_ORDER = "SET_ORDER";

export { GET_CAR_DATA, SEARCH_CAR_DATA, EMAIL_DATA, SET_ORDER };
